#include <iostream>
using namespace std;

class Employee{
    // body of class
    //members - attributes and behaviour
    // Access Modifier - Public,Private and Protected
    // Everthing in C++ private by default
    //object(instance) of class

public:
    // Atrributes
    string Name;
    string Company;
    int Age;

    // Class method - basically a function
    void IntroduceYourself(){
        cout<<"Name - "<<Name<<endl;
        cout<<"Company - "<<Company<<endl;
        cout<<"Age - "<<Age<<endl;
    }

    // Constructor - Special type of method that
    // is invoked each time the object of class is created.
    // Default constructor - a constructor that is automatically generated by compiler
    // Rules to create constructor-
    // 1. constructor doesn't have return type
    // 2. Same name as class, it belongs to
    // 3. Constructors are public
    Employee(string name, string company, int age)
    {
        Name = name;
        Company = company;
        Age = age;
    }

};
int main()
{
    // how to create object
    // datatype + name to var
    //int number;
    Employee emp1 = Employee("Satyam","Meta",25);
    // emp1.Name="Satyam";
    // emp1.Company="Meta";
    // emp1.Age=25;
    emp1.IntroduceYourself();

    
}